#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

START=99
USE_PROCD=1

PROC=/bin/read_gpio

start_service() {
	echo 0 > /sys/class/gpio/export
	echo in > /sys/class/gpio/gpio0/direction
	echo both > /sys/class/gpio/gpio0/edge
	procd_open_instance
	procd_set_param respawn -3 -5 -1
	procd_set_param command $PROC
	procd_close_instance
}

reload_service() {
	stop
	sleep 3
	start
}

