#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

START=90
USE_PROCD=1
LOG="/tmp/remotecontrol.file"

PROC=/usr/bin/remote_control

ipaddr="39.98.165.253"
subtopic="sub"
pubtopic="pub"
switch="2"
buzzer="4"
switchsleep="1"
buzzersleep="50"

get_params(){              
        config_get $2 $1 $3 
}

start_service() {
	config_load remote_control	
	config_foreach get_params door subtopic subtopic
	config_foreach get_params door pubtopic pubtopic
	config_foreach get_params door ipaddr ipaddr
	config_foreach get_params door switch switch
	config_foreach get_params door buzzer buzzer
	config_foreach get_params door switchsleep switchsleep
	config_foreach get_params door buzzersleep buzzersleep
	
	echo $ipaddr $subtopic $pubtopic $buzzer $switch $switchsleep $buzzersleep
	echo $switch > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio$switch/direction
	echo $buzzer > /sys/class/gpio/export
	echo out > /sys/class/gpio/gpio$buzzer/direction
	echo 1 > /sys/class/gpio/gpio$buzzer/value

	
	procd_open_instance 
	procd_set_param respawn -3 -5 -1
	procd_set_param command $PROC

	procd_append_param command -h $ipaddr -t $subtopic -tp $pubtopic -switch $switch -ssleep $switchsleep -buzzer $buzzer -bsleep $buzzersleep
	procd_close_instance
}

service_triggers()
{
    procd_add_reload_trigger "remote_control"
}

reload_service() {
	stop
	sleep 3
	start
}
