#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

START=90
USE_PROCD=1

#tcp conf
ipaddr=""
port=""

PROC=/usr/bin/connecttoha

proc_arg=""

get_params(){
	config_get $2 $1 $3
}

start_service() {
#        . /lib/functions.sh
#        . /lib/functions/network.sh

	config_load smarthome

	config_foreach get_params server ipaddr ipaddr
	config_foreach get_params server port port
	echo $ipaddr $port	
#	procd_open_instance 
#	procd_set_param respawn
#	procd_set_param command $PROC

#	procd_close_instance
}

service_triggers()
{
    procd_add_reload_trigger "smarthome"
}

reload_service() {
	stop
	start
}
