#!/bin/sh /etc/rc.common
# Copyright (C) 2008 OpenWrt.org

START=90
USE_PROCD=1

#tcp conf
ipaddr=""
port=""

PROC=/usr/bin/haclient
proc_arg=""

get_params(){
	config_get $2 $1 $3
}

start_service() {
	#        . /lib/functions.sh
	#        . /lib/functions/network.sh

	config_load smarthome

	/bin/setuart /dev/ttyS1 9600 8 N 1

	macaddr=$(uci get network.wan_dev.macaddr | sed -e 's/://g')
	echo $macaddr

	procd_open_instance
	procd_set_param respawn 5 -1 -1
	procd_set_param command $PROC
	procd_append_param command -h 39.98.165.253 -t $macaddr/# -v
	procd_close_instance
}

service_triggers()
{
	procd_add_reload_trigger "smarthome"
}

stop() {
    kill -s SIGTERM  $(ps w|grep haclient | grep -v grep | awk '{print $1}')
}

reload_service() {
	stop
	start
}
